import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft,ArrowRight,BarChart3,Bell,CheckCircle2,Crown,ExternalLink,Gauge,LockKeyhole,MapPin,ShieldAlert,TrendingUp } from "lucide-react";
import { vehicles } from "@/lib/vehicles";

const text={
 fr:{back:"Retour aux enchères",watch:"Suivre",source:"Voir l’annonce source",diesel:"Diesel",auto:"Automatique",current:"Offre actuelle",start:"Prix de départ",open:"Voir l’enchère",score:"Score LotRank",verdict:"À suivre",scoreInfo:"Évalué selon le prix, la demande, le risque et le potentiel de revente.",analysis:"Analyse LotRank",free:"Résumé gratuit",market:"Fourchette du marché",similar:"Selon les véhicules similaires",risk:"Risque global",riskInfo:"Selon les données de l’annonce",advantage:"Avantage prix",currentInfo:"Par rapport à l’offre actuelle",reasons:"Pourquoi cette opportunité",r1:"Prix inférieur aux annonces similaires",r2:"Forte demande sur le marché de l’occasion",r3:"Analyse détaillée de la revente",r4:"Comparaison régionale",cost:"Coût total",vehicle:"Prix du véhicule",fees:"Commission + transport",total:"Total estimé",unlock:"Voir tous les coûts",upgrade:"Passer à PRO",chart:"Évolution du prix des véhicules similaires",proAnalysis:"Analyse PRO",chartInfo:"Le graphique détaillé et les données sur 90 jours sont réservés aux membres PRO."},
 en:{back:"Back to auctions",watch:"Watch",source:"Open source listing",diesel:"Diesel",auto:"Automatic",current:"Current bid",start:"Starting price",open:"View auction",score:"LotRank Score",verdict:"Worth tracking",scoreInfo:"Based on price, demand, risk and resale potential.",analysis:"LotRank Analysis",free:"Free summary",market:"Market range",similar:"Based on similar vehicles",risk:"Overall risk",riskInfo:"Based on listing data",advantage:"Price advantage",currentInfo:"Compared with current bid",reasons:"Why it stands out",r1:"Priced below similar listings",r2:"Strong used-market demand",r3:"Detailed resale analysis",r4:"Regional comparison",cost:"Total cost",vehicle:"Vehicle price",fees:"Fees + transport",total:"Estimated total",unlock:"See all costs",upgrade:"Upgrade to PRO",chart:"Similar vehicle price movement",proAnalysis:"PRO analysis",chartInfo:"Detailed charts and 90-day data are for PRO members."},
 zh:{back:"返回拍卖",watch:"关注",source:"查看原始拍卖",diesel:"柴油",auto:"自动挡",current:"当前出价",start:"起拍价",open:"查看拍卖",score:"LotRank 评分",verdict:"值得关注",scoreInfo:"根据价格、需求、风险和转售潜力评估。",analysis:"LotRank 分析",free:"免费摘要",market:"市场价格区间",similar:"基于同类车辆",risk:"总体风险",riskInfo:"根据拍卖数据",advantage:"价格优势",currentInfo:"与当前出价相比",reasons:"机会亮点",r1:"价格低于同类车辆",r2:"二手市场需求强劲",r3:"详细转售分析",r4:"地区比较",cost:"总成本",vehicle:"车辆价格",fees:"手续费和运输",total:"预计总额",unlock:"查看全部成本",upgrade:"升级 PRO",chart:"同类车辆价格走势",proAnalysis:"PRO 分析",chartInfo:"详细图表和90天数据仅供 PRO 会员使用。"}
} as const;

export default async function Vehicle({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{lang?:string}>}){
 const {id}=await params; const q=await searchParams; const lang=q.lang==="en"||q.lang==="zh"?q.lang:"fr"; const t=text[lang];
 const v=vehicles.find(x=>x.id===id); if(!v)notFound();
 return <main className="detail"><nav className="detailNav wrap"><Link className="logo" href={`/?lang=${lang}`}><BarChart3/>LotRank</Link><Link href={`/?lang=${lang}`}><ArrowLeft/>{t.back}</Link><div><button><Bell/>{t.watch}</button><button className="green">{t.source}<ExternalLink/></button></div></nav><section className="detailHero"><div className="wrap detailTop"><div className="bigPhoto"><img src={v.image} alt={`${v.brand} ${v.model}`}/><span>● LIVE {v.time}</span></div><div className="summary"><small>{v.year} · {t.diesel} · {t.auto}</small><h1>{v.brand} {v.model}</h1><p><MapPin/>{v.place}<span>{v.km}</span></p><div><span>{t.current}<b>{v.price}</b></span><span>{t.start}<b>{v.start}</b></span></div><button className="green">{t.open}<ArrowRight/></button></div><aside className="scoreCard"><strong>{v.score}<small>/100</small></strong><span>{t.score}</span><b>{t.verdict}</b><p>{t.scoreInfo}</p></aside></div></section><section className="detailBody"><div className="wrap detailGrid"><article className="analysis wide"><header><span><Gauge/>{t.analysis}</span><b>{t.free}</b></header><div className="three"><p><small>{t.market}</small><b>€21.000 – €24.200</b><span>{t.similar}</span></p><p><small>{t.risk}</small><b className="orange">Moyen</b><span>{t.riskInfo}</span></p><p><small>{t.advantage}</small><b className="good">+{v.gain}%</b><span>{t.currentInfo}</span></p></div></article><article className="analysis"><header><span><CheckCircle2/>{t.reasons}</span></header><ul><li><CheckCircle2/>{t.r1}</li><li><CheckCircle2/>{t.r2}</li><li className="muted"><LockKeyhole/>{t.r3}<b>PRO</b></li><li className="muted"><LockKeyhole/>{t.r4}<b>PRO</b></li></ul></article><article className="analysis pro"><header><span><Crown/>{t.cost}</span><b>PRO</b></header><div className="blur"><p>{t.vehicle}<b>{v.price}</b></p><p>{t.fees}<b>€••••</b></p><p>{t.total}<b>€••••</b></p></div><div className="overlay"><LockKeyhole/><b>{t.unlock}</b><button>{t.upgrade}</button></div></article><article className="analysis wide chart"><header><span><TrendingUp/>{t.chart}</span><b>{t.proAnalysis}</b></header><div className="chartLine"/><p><LockKeyhole/> {t.chartInfo}</p></article></div></section></main>
}
